<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>MyTemplate.API</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AspNetCore.HealthChecks.Sqlite" Version="8.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.14" />
    <PackageReference Include="Serilog.AspNetCore" Version="8.0.3" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.0.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="6.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.9.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MyTemplate.Application\LaunchKitNET.Application.csproj" />
    <ProjectReference Include="..\MyTemplate.Domain\LaunchKitNET.Domain.csproj" />
    <ProjectReference Include="..\MyTemplate.Infrastructure\LaunchKitNET.Infrastructure.csproj" />
    <ProjectReference Include="..\MyTemplate.Shared\LaunchKitNET.Shared.csproj" />
  </ItemGroup>

</Project>
